
server:
    host: 0.0.0.0
    port: 5001
    debug: False
    secret_key: "rzbw4hb12yz29ey7530j"

redis:
    host: 192.168.1.5
    port: 6379
    password: "Dingtalk1234561017"
    db: 0

admin:
    email: abb1234aabb@gmail.com
    password: admin