
server:
    host: 0.0.0.0
    port: 5001
    debug: False
    secret_key: "rzbw4hb12yz29ey7530j"

redis:
    host: 192.168.1.3
    port: 6379
    password: "Dingtalk1234561017"
    db: 0

email:
    smtp_host: smtp.163.com
    smtp_port: 465
    smtp_user: abb1234aabb@163.com
    smtp_password: "ENWHVUCJXFARZRBA"
    smtp_sender: paimon@alistnas.top

admin:
    email: abb1234aabb@gmail.com
    password: admin